/**
 * The backlog as a person reads it: the counts, and the markdown.
 *
 * The render is deterministic on purpose. `lookout backlog check` byte-compares
 * what it would write against what is on disk to tell whether the document has
 * drifted from the data, and a render that reordered anything by chance would
 * make that comparison meaningless.
 */
import { clusterKeyOf } from "../fix/cluster.js";
import type { Severity } from "../types.js";
import type { Backlog, BacklogFinding, FindingStatus } from "./lib.js";

// Markdown report (deterministic render so `check` can byte-compare)

const SEVERITY_ORDER: Record<Severity, number> = { critical: 0, high: 1, medium: 2, low: 3 };

export function stats(backlog: Backlog): {
  byStatus: Record<FindingStatus, number>;
  bySeverityOpen: Record<Severity, number>;
  total: number;
} {
  const byStatus: Record<FindingStatus, number> = { open: 0, fixed: 0, "by-design": 0, blocked: 0 };
  const bySeverityOpen: Record<Severity, number> = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const f of Object.values(backlog.findings)) {
    byStatus[f.status]++;
    if (f.status === "open") bySeverityOpen[f.severity]++;
  }
  return { byStatus, bySeverityOpen, total: Object.keys(backlog.findings).length };
}

export function renderMarkdown(backlog: Backlog): string {
  const s = stats(backlog);
  // The number people actually use, on the report people actually read. It is
  // also the folder holding this finding's screenshots and its history.
  const idFor = (f: BacklogFinding): string => {
    const key = clusterKeyOf(f);
    const record = Object.values(backlog.issues ?? {}).find((r) => r.key === key);
    return record?.id ?? "";
  };
  const all = Object.values(backlog.findings);
  const sorted = (list: BacklogFinding[]) =>
    [...list].sort(
      (a, b) =>
        SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity] ||
        a.fingerprint.localeCompare(b.fingerprint),
    );
  // The issue number links to the document that carries everything about it;
  // the fingerprint, which nobody reads and every command takes, is listed
  // once under Identities instead of widening every row.
  const issueCell = (f: BacklogFinding): string => {
    const id = idFor(f);
    return id ? `[${id}](issues/${id}/Issue.md)` : "";
  };
  const row = (f: BacklogFinding) =>
    `| ${issueCell(f)} | ${f.severity} | ${f.channel}${f.verified ? " (verified)" : ""} | ${f.title.replace(/\|/g, "\\|")} | ${f.evidence[f.evidence.length - 1]?.path ?? ""} |`;

  const lines: string[] = [
    "<!-- Generated by `lookout backlog regen`. Do not edit by hand. -->",
    "",
    `# lookout backlog: ${backlog.project}`,
    "",
    `Updated ${backlog.updatedAt}. ${s.total} finding(s) in ${Object.keys(backlog.issues ?? {}).length} issue(s): ` +
      `${s.byStatus.open} open, ${s.byStatus.fixed} fixed, ${s.byStatus["by-design"]} by design, ${s.byStatus.blocked} blocked.`,
    `Open by severity: ${s.bySeverityOpen.critical} critical, ${s.bySeverityOpen.high} high, ${s.bySeverityOpen.medium} medium, ${s.bySeverityOpen.low} low.`,
    "",
  ];

  const section = (title: string, list: BacklogFinding[], withReason: boolean) => {
    lines.push(`## ${title}`, "");
    if (list.length === 0) {
      lines.push("None.", "");
      return;
    }
    lines.push(
      "| issue | severity | channel | title | evidence |",
      "| --- | --- | --- | --- | --- |",
    );
    for (const f of sorted(list)) {
      lines.push(row(f));
      if (withReason && f.reason) {
        lines.push(`| | | | reason: ${f.reason.replace(/\|/g, "\\|")} | |`);
      }
    }
    lines.push("");
  };

  section("Open", all.filter((f) => f.status === "open"), false);
  section("Blocked", all.filter((f) => f.status === "blocked"), true);
  section("By design", all.filter((f) => f.status === "by-design"), true);
  section("Fixed", all.filter((f) => f.status === "fixed"), false);

  lines.push("## Identities", "");
  if (all.length === 0) lines.push("None.", "");
  else {
    lines.push("The fingerprint behind each row: what `lookout backlog set` takes, and what the ledger is keyed by.", "");
    for (const f of sorted(all)) lines.push(`- ${issueCell(f) ? `${issueCell(f)} ` : ""}\`${f.fingerprint}\``);
    lines.push("");
  }

  return lines.join("\n");
}
