/**
 * `Issue.json`: the issue's record as a machine reads it.
 *
 * Deliberately flat and self-contained: someone reading `Issue.json` should
 * not need the backlog open beside it. It is generated with the document from
 * the same inputs, and it is the document's twin rather than its summary: a
 * fact the markdown states belongs in here too.
 */
import type { BacklogFinding, IssueRecord } from "../backlog/lib.js";
import type { FixCluster } from "../fix/cluster.js";
import { clusterLabel } from "../fix/brief.js";

/** Which side of the fix a dossier picture is of. */
export type ShotSide = "pre" | "post";

/** One screenshot as the dossier records it. */
export interface IssueShot {
  /** Filename inside img/<side>/, flattened from the evidence-relative path. */
  file: string;
  /** Which subfolder it is in, and what it is a picture of. */
  side: ShotSide;
  route: string;
  formFactor: string;
  scheme: string;
  state: string;
}

export interface IssueDocument {
  generated: string;
  id: string;
  key: string;
  title: string;
  label: string;
  severity: string;
  category: string;
  status: "open" | "blocked" | "fixed" | "archived";
  channel: string;
  verified: boolean;
  routes: string[];
  defects: { attribute: string; severity: string; title: string; problem: string }[];
  fingerprints: string[];
  shots: IssueShot[];
  acceptance: IssueRecord["acceptance"];
  attemptsSpent: number;
  createdAt: string;
  causedBy?: IssueRecord["causedBy"];
}

const GENERATED =
  "Generated by lookout from backlog.json. Safe to delete; regenerated on the next save. " +
  "state.json, frames.json, the img/ folder and handoff.command in this folder are NOT " +
  "generated: they are the record itself and are never rewritten from anything else.";

/** The issue's own status, from its findings alone. */
export function statusOf(members: BacklogFinding[]): IssueDocument["status"] {
  if (members.some((m) => m.status === "open")) return "open";
  if (members.some((m) => m.status === "blocked")) return "blocked";
  if (members.some((m) => m.status === "fixed")) return "fixed";
  return "archived";
}

export function buildIssueDocument(
  cluster: FixCluster,
  record: IssueRecord,
  shots: IssueShot[],
): IssueDocument {
  return {
    generated: GENERATED,
    id: record.id,
    key: record.key,
    title: cluster.title,
    label: clusterLabel(cluster),
    severity: cluster.severity,
    category: cluster.category,
    status: statusOf(cluster.members),
    channel: cluster.channel,
    verified: cluster.verified,
    routes: cluster.routes,
    defects: cluster.defects,
    fingerprints: cluster.fingerprints,
    shots,
    acceptance: record.acceptance ?? [],
    attemptsSpent: cluster.attemptsSpent,
    createdAt: record.createdAt,
    ...(record.causedBy ? { causedBy: record.causedBy } : {}),
  };
}
