/**
 * The issue folder: everything about one defect, in one place, named by its id.
 *
 *   .lookout/issues/418203/
 *     Issue.json        generated: the record, machine-readable
 *     Issue.md          generated: the same thing for a person or an agent
 *     img/pre/          truth: the defect as filed, frozen once per view
 *     img/post/         truth: the same views once a fix was ruled on
 *     frames.json       truth: what each frozen picture is a picture of
 *     state.json        truth: attempts, written by verify-fix
 *     handoff.command   written when somebody opens the issue in a tool
 *
 * `backlog.json` stays the single source of truth for the record. Everything
 * marked generated here is a projection of it, rewritten on every save exactly
 * as BACKLOG.md already was, and safe to delete. Everything marked truth is
 * written by the run that produced it and never regenerated: the frozen
 * pictures in particular are the only copy of the defect anybody keeps, since
 * the capture workspace overwrites its file for a view on every re-capture.
 *
 * Screenshots are COPIED into the folder rather than linked. One workspace
 * shot backs several issues, and the workspace is routinely cleaned; a dossier
 * whose pictures are links into it is a dossier full of dead links the first
 * time that happens. Freezing writes straight into `img/` (issues/frames.ts),
 * so the only copying left here is the live-workspace guess for an issue
 * nothing could ever freeze.
 */
import { copyFile, mkdir, readdir, rename, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { basename, join } from "node:path";
import { evidenceDir } from "../config.js";
import { wasPhotographed, type Backlog, type BacklogFinding, type IssueRecord } from "../backlog/lib.js";
import type { FixCluster } from "../fix/cluster.js";
import { clusterLabel } from "../fix/brief.js";
import { issuesOf } from "./registry.js";
import {
  flatShotName,
  issueDirFor,
  issueImgDir,
  ISSUE_DOC_FILE,
  ISSUE_RECORD_FILE,
} from "./paths.js";
import { renderIssueDocument } from "./document.js";
import { ensureBeforeFrames, type Frame, type FrameSet } from "./frames.js";
import type { ResolvedConfig } from "../types.js";

/** Which side of the fix a dossier picture is of. */
export type ShotSide = "pre" | "post";

/** One screenshot as the dossier records it. */
export interface IssueShot {
  /** Filename inside img/<side>/, flattened from the evidence-relative path. */
  file: string;
  /** Which subfolder it is in, and what it is a picture of. */
  side: ShotSide;
  route: string;
  formFactor: string;
  scheme: string;
  state: string;
}

/**
 * The generated record. Deliberately flat and self-contained: someone reading
 * `Issue.json` should not need the backlog open beside it.
 */
export interface IssueDocument {
  generated: string;
  id: string;
  key: string;
  title: string;
  label: string;
  severity: string;
  category: string;
  status: "open" | "blocked" | "fixed" | "archived";
  channel: string;
  verified: boolean;
  routes: string[];
  defects: { attribute: string; severity: string; title: string; problem: string }[];
  fingerprints: string[];
  shots: IssueShot[];
  acceptance: IssueRecord["acceptance"];
  attemptsSpent: number;
  createdAt: string;
  causedBy?: IssueRecord["causedBy"];
}

const GENERATED =
  "Generated by lookout from backlog.json. Safe to delete; regenerated on the next save. " +
  "state.json, frames.json, the img/ folder and handoff.command in this folder are NOT " +
  "generated: they are the record itself and are never rewritten from anything else.";

/** The issue's own status, from its findings alone. */
function statusOf(members: BacklogFinding[]): IssueDocument["status"] {
  if (members.some((m) => m.status === "open")) return "open";
  if (members.some((m) => m.status === "blocked")) return "blocked";
  if (members.some((m) => m.status === "fixed")) return "fixed";
  return "archived";
}

/** One picture to copy in: where it is now, and what it should be called here. */
interface ShotSource {
  file: string;
  path: string;
  route: string;
  formFactor: string;
  scheme: string;
  state: string;
}

/** The frozen frames of one side, as the record lists them. Already in img/. */
function frozenSources(frames: Frame[]): ShotSource[] {
  return frames.map((f) => ({
    file: basename(f.path),
    path: f.path,
    route: f.route,
    formFactor: f.formFactor,
    scheme: f.scheme,
    state: f.state ?? "",
  }));
}

/**
 * The live workspace paths, which is all there is for an issue nothing could
 * freeze.
 *
 * A code-channel finding has no screenshot at all, so it contributes nothing
 * here and the issue's folder simply has no pictures in it.
 */
function liveSources(cluster: FixCluster): ShotSource[] {
  const out: ShotSource[] = [];
  const seen = new Set<string>();
  for (const m of cluster.members) {
    const ev = m.evidence[m.evidence.length - 1];
    if (!ev || !wasPhotographed(m) || seen.has(ev.path)) continue;
    seen.add(ev.path);
    out.push({
      file: flatShotName(ev.path),
      path: ev.path,
      route: m.route,
      formFactor: m.formFactor,
      scheme: m.scheme,
      state: m.state,
    });
  }
  return out;
}

/**
 * Settle the img/ folder, one subfolder per side of the fix.
 *
 * Frozen frames already live here: freezing writes them in place, so where a
 * side is frozen there is nothing to copy, only strays to prune (a picture
 * that stopped being any finding's evidence, or a name from an older layout).
 * That keeps the dossier and the card showing the same picture of the same
 * view, because they are the same file.
 *
 * Where nothing was ever frozen, the live workspace is a guess at what the
 * defect looked like, and a guess neither overwrites nor prunes anything: a
 * file already in `img/pre/` is the older picture, and on an issue nothing
 * could freeze it may be the only copy of the defect left anywhere.
 */
async function syncShots(
  resolved: ResolvedConfig,
  id: string,
  cluster: FixCluster,
  frames: FrameSet,
): Promise<IssueShot[]> {
  const evDir = evidenceDir(resolved);
  const dir = issueImgDir(resolved, id);
  const frozen = frames.before.length > 0;
  const sides: [ShotSide, ShotSource[]][] = [
    ["pre", frozen ? frozenSources(frames.before) : liveSources(cluster)],
    ["post", frozenSources(frames.after)],
  ];

  const shots: IssueShot[] = [];
  for (const [side, sources] of sides) {
    const sideDir = join(dir, side);
    const wanted = new Set<string>();
    for (const s of sources) {
      if (wanted.has(s.file)) continue;
      wanted.add(s.file);
      shots.push({ file: s.file, side, route: s.route, formFactor: s.formFactor, scheme: s.scheme, state: s.state });
      if (side !== "pre" || frozen) continue;
      const src = join(evDir, s.path);
      const dest = join(sideDir, s.file);
      if (!existsSync(src) || existsSync(dest)) continue;
      await mkdir(sideDir, { recursive: true });
      // A screenshot that cannot be copied does not stop the record being
      // written; the document names the workspace's path as well.
      await copyFile(src, dest).catch(() => {});
    }
    if (side === "pre" && !frozen) continue;
    for (const entry of await readdir(sideDir).catch(() => [] as string[])) {
      if (entry.endsWith(".png") && !wanted.has(entry)) await rm(join(sideDir, entry), { force: true });
    }
  }
  return shots;
}

async function writeAtomic(path: string, body: string): Promise<void> {
  const tmp = `${path}.tmp`;
  await writeFile(tmp, body);
  await rename(tmp, path);
}

/**
 * Fold a folder written by an older lookout into the current layout. The
 * record and document renames differ only by case (issue.json -> Issue.json,
 * ISSUE.md -> Issue.md), and on a case-insensitive filesystem (the macOS
 * default) both spellings resolve to the same directory entry; so legacy
 * names are matched byte-exactly against readdir and removed BEFORE the new
 * names are written, because removing them afterwards would delete the fresh
 * files. shots/ is moved into img/ rather than deleted: the evidence store
 * these were copied from is gitignored and routinely cleaned, and stale
 * pixels beat missing ones.
 */
async function migrateLegacyLayout(dir: string): Promise<void> {
  const entries = await readdir(dir).catch(() => [] as string[]);
  for (const name of ["issue.json", "issue.json.tmp", "ISSUE.md", "ISSUE.md.tmp"]) {
    if (entries.includes(name)) await rm(join(dir, name), { force: true });
  }
  const img = join(dir, "img");
  if (entries.includes("shots")) {
    const legacy = join(dir, "shots");
    await mkdir(img, { recursive: true });
    for (const file of await readdir(legacy).catch(() => [] as string[])) {
      if (!existsSync(join(img, file))) {
        await rename(join(legacy, file), join(img, file)).catch(() => {});
      }
    }
    await rm(legacy, { recursive: true, force: true });
  }

  // img/ held one flat pile before there were two sides to a picture. Those
  // files are the older copy of the defect, which is exactly what `pre` means,
  // so they are moved rather than dropped: for an issue filed before frames
  // existed, this pile is the only picture of it anybody kept.
  const pre = join(img, "pre");
  for (const file of await readdir(img).catch(() => [] as string[])) {
    if (!file.endsWith(".png")) continue;
    await mkdir(pre, { recursive: true });
    if (!existsSync(join(pre, file))) await rename(join(img, file), join(pre, file)).catch(() => {});
  }
}

/** Write one issue's folder: its record, its document, and its screenshots. */
export async function materializeIssue(
  resolved: ResolvedConfig,
  cluster: FixCluster,
  record: IssueRecord,
): Promise<string> {
  // Where the folder belongs is the record's call, and the folder follows it
  // here rather than at the moment somebody clicks archive: one mechanism, run
  // on every save, so a record and its folder cannot drift apart.
  const dir = issueDirFor(resolved, record.id, !!record.archived);
  const other = issueDirFor(resolved, record.id, !record.archived);
  if (existsSync(other) && !existsSync(dir)) {
    await mkdir(join(dir, ".."), { recursive: true });
    // A move rather than a copy: two folders for one issue would be two
    // answers to "where is this", and state.json lives in only one of them.
    await rename(other, dir).catch(() => {});
  }
  await mkdir(dir, { recursive: true });
  await migrateLegacyLayout(dir);
  // Freeze the defect first: this is the moment the workspace still holds the
  // pixels the finding was judged from, and every write path reaches it, so no
  // issue arrives on the board without a picture of itself.
  const frames = await ensureBeforeFrames(resolved, cluster);
  const shots = await syncShots(resolved, record.id, cluster, frames);

  const doc: IssueDocument = {
    generated: GENERATED,
    id: record.id,
    key: record.key,
    title: cluster.title,
    label: clusterLabel(cluster),
    severity: cluster.severity,
    category: cluster.category,
    status: statusOf(cluster.members),
    channel: cluster.channel,
    verified: cluster.verified,
    routes: cluster.routes,
    defects: cluster.defects,
    fingerprints: cluster.fingerprints,
    shots,
    acceptance: record.acceptance ?? [],
    attemptsSpent: cluster.attemptsSpent,
    createdAt: record.createdAt,
    ...(record.causedBy ? { causedBy: record.causedBy } : {}),
  };
  await writeAtomic(join(dir, ISSUE_RECORD_FILE), JSON.stringify(doc, null, 2));

  const { markdown } = await renderIssueDocument(resolved, cluster, record);
  await writeAtomic(join(dir, ISSUE_DOC_FILE), markdown);
  return dir;
}

/**
 * Rewrite every issue's folder from the backlog. Called on save, so the folders
 * never drift from the record they project.
 */
export async function materializeIssues(resolved: ResolvedConfig, backlog: Backlog): Promise<void> {
  const clusters = issuesOf(backlog);
  const byKey = new Map(Object.values(backlog.issues ?? {}).map((r) => [r.key, r]));
  for (const cluster of clusters) {
    const record = byKey.get(cluster.key);
    if (record) await materializeIssue(resolved, cluster, record);
  }
}
