/**
 * The issue folder: everything about one defect, in one place, named by its id.
 *
 *   .lookout/issues/418203/
 *     Issue.json        generated: the record, machine-readable
 *     Issue.md          generated: the same thing for a person or an agent
 *     img/              generated: the screenshots it was filed against
 *     state.json        truth: attempts, written by verify-fix
 *     handoff.command   written when somebody opens the issue in a tool
 *
 * `backlog.json` stays the single source of truth. Everything marked generated
 * here is a projection of it, rewritten on every save exactly as BACKLOG.md
 * already was, and safe to delete. Everything marked truth is written once by
 * the run that produced it and never regenerated.
 *
 * Screenshots are COPIED rather than linked. One shot backs several issues, so
 * the evidence store stays the canonical home; but a dossier whose pictures are
 * links into a directory the project gitignores is a dossier full of dead links
 * the first time somebody cleans it. Stale pixels beat missing ones.
 */
import { copyFile, mkdir, readdir, rename, rm, writeFile } from "node:fs/promises";
import { existsSync, statSync } from "node:fs";
import { join } from "node:path";
import { evidenceDir } from "../config.js";
import type { Backlog, BacklogFinding, IssueRecord } from "../backlog/lib.js";
import type { FixCluster } from "../fix/cluster.js";
import { clusterLabel } from "../fix/brief.js";
import { issuesOf } from "./registry.js";
import { flatShotName, issueDir, issueImgDir, ISSUE_DOC_FILE, ISSUE_RECORD_FILE } from "./paths.js";
import { renderIssueDocument } from "./document.js";
import type { ResolvedConfig } from "../types.js";

/** One screenshot as the dossier records it. */
export interface IssueShot {
  /** Filename inside img/, flattened from the evidence-relative path. */
  file: string;
  route: string;
  formFactor: string;
  scheme: string;
  state: string;
}

/**
 * The generated record. Deliberately flat and self-contained: someone reading
 * `Issue.json` should not need the backlog open beside it.
 */
export interface IssueDocument {
  generated: string;
  id: string;
  key: string;
  title: string;
  label: string;
  severity: string;
  category: string;
  status: "open" | "blocked" | "fixed" | "archived";
  channel: string;
  verified: boolean;
  routes: string[];
  defects: { attribute: string; severity: string; title: string; problem: string }[];
  fingerprints: string[];
  shots: IssueShot[];
  acceptance: IssueRecord["acceptance"];
  attemptsSpent: number;
  createdAt: string;
  causedBy?: IssueRecord["causedBy"];
}

const GENERATED =
  "Generated by lookout from backlog.json. Safe to delete; regenerated on the next save. " +
  "state.json and handoff.command in this folder are NOT generated and are never rewritten.";

/** The issue's own status, from its findings alone. */
function statusOf(members: BacklogFinding[]): IssueDocument["status"] {
  if (members.some((m) => m.status === "open")) return "open";
  if (members.some((m) => m.status === "blocked")) return "blocked";
  if (members.some((m) => m.status === "fixed")) return "fixed";
  return "archived";
}

/**
 * Copy in the screenshots this issue was filed against, and drop any that no
 * longer belong to it. Unchanged files are left alone: a save runs on every
 * merge, and re-copying megabytes of identical pixels would make the cheap
 * operation the expensive one.
 */
async function syncShots(resolved: ResolvedConfig, id: string, cluster: FixCluster): Promise<IssueShot[]> {
  const evDir = evidenceDir(resolved);
  const dir = issueImgDir(resolved, id);
  await mkdir(dir, { recursive: true });

  const shots: IssueShot[] = [];
  const wanted = new Set<string>();
  for (const m of cluster.members) {
    const ev = m.evidence[m.evidence.length - 1];
    if (!ev) continue;
    const file = flatShotName(ev.path);
    if (wanted.has(file)) continue;
    wanted.add(file);
    shots.push({ file, route: m.route, formFactor: m.formFactor, scheme: m.scheme, state: m.state });

    const src = join(evDir, ev.path);
    const dest = join(dir, file);
    if (!existsSync(src)) continue;
    try {
      const a = statSync(src);
      const b = existsSync(dest) ? statSync(dest) : null;
      if (b && b.size === a.size && b.mtimeMs >= a.mtimeMs) continue;
      await copyFile(src, dest);
    } catch {
      // A screenshot that cannot be copied does not stop the record being
      // written; the document names the evidence store's path as well.
    }
  }

  for (const entry of await readdir(dir).catch(() => [])) {
    if (entry.endsWith(".png") && !wanted.has(entry)) await rm(join(dir, entry), { force: true });
  }
  return shots;
}

async function writeAtomic(path: string, body: string): Promise<void> {
  const tmp = `${path}.tmp`;
  await writeFile(tmp, body);
  await rename(tmp, path);
}

/**
 * Fold a folder written by an older lookout into the current layout. The
 * record and document renames differ only by case (issue.json -> Issue.json,
 * ISSUE.md -> Issue.md), and on a case-insensitive filesystem (the macOS
 * default) both spellings resolve to the same directory entry; so legacy
 * names are matched byte-exactly against readdir and removed BEFORE the new
 * names are written, because removing them afterwards would delete the fresh
 * files. shots/ is moved into img/ rather than deleted: the evidence store
 * these were copied from is gitignored and routinely cleaned, and stale
 * pixels beat missing ones.
 */
async function migrateLegacyLayout(dir: string): Promise<void> {
  const entries = await readdir(dir).catch(() => [] as string[]);
  for (const name of ["issue.json", "issue.json.tmp", "ISSUE.md", "ISSUE.md.tmp"]) {
    if (entries.includes(name)) await rm(join(dir, name), { force: true });
  }
  if (!entries.includes("shots")) return;

  const legacy = join(dir, "shots");
  const img = join(dir, "img");
  await mkdir(img, { recursive: true });
  for (const file of await readdir(legacy).catch(() => [] as string[])) {
    if (!existsSync(join(img, file))) {
      await rename(join(legacy, file), join(img, file)).catch(() => {});
    }
  }
  await rm(legacy, { recursive: true, force: true });
}

/** Write one issue's folder: its record, its document, and its screenshots. */
export async function materializeIssue(
  resolved: ResolvedConfig,
  cluster: FixCluster,
  record: IssueRecord,
): Promise<string> {
  const dir = issueDir(resolved, record.id);
  await mkdir(dir, { recursive: true });
  await migrateLegacyLayout(dir);
  const shots = await syncShots(resolved, record.id, cluster);

  const doc: IssueDocument = {
    generated: GENERATED,
    id: record.id,
    key: record.key,
    title: cluster.title,
    label: clusterLabel(cluster),
    severity: cluster.severity,
    category: cluster.category,
    status: statusOf(cluster.members),
    channel: cluster.channel,
    verified: cluster.verified,
    routes: cluster.routes,
    defects: cluster.defects,
    fingerprints: cluster.fingerprints,
    shots,
    acceptance: record.acceptance ?? [],
    attemptsSpent: cluster.attemptsSpent,
    createdAt: record.createdAt,
    ...(record.causedBy ? { causedBy: record.causedBy } : {}),
  };
  await writeAtomic(join(dir, ISSUE_RECORD_FILE), JSON.stringify(doc, null, 2));

  const { markdown } = await renderIssueDocument(resolved, cluster, record);
  await writeAtomic(join(dir, ISSUE_DOC_FILE), markdown);
  return dir;
}

/**
 * Rewrite every issue's folder from the backlog. Called on save, so the folders
 * never drift from the record they project.
 */
export async function materializeIssues(resolved: ResolvedConfig, backlog: Backlog): Promise<void> {
  const clusters = issuesOf(backlog);
  const byKey = new Map(Object.values(backlog.issues ?? {}).map((r) => [r.key, r]));
  for (const cluster of clusters) {
    const record = byKey.get(cluster.key);
    if (record) await materializeIssue(resolved, cluster, record);
  }
}
